### ISSUE TITLE
Broken example: proxy.js

### ISSUE THREAD

**Issue by bnb** [ebidel/try-puppeteer#38] opened 2019-01-13 13:34 UTC
Looks like proxy.js is broken as a default right now:

![image](https://user-images.githubusercontent.com/502396/51085941-01e0c700-170e-11e9-98e5-93c2c1251fd2.png)

Just wanted to report so y'all are aware! 🙏

**Comment by michalstanko** [comment] 2019-02-08 09:10
The same applies to screenshot-fullpage.js example, which also has a `require()`

Thanks

**Comment by ebidel** [comment] 2019-02-11 23:13
Dupe of https://github.com/ebidel/try-puppeteer/issues/3

**Closed by ebidel** 2019-02-11 23:13 UTC
