### ISSUE TITLE
Shareable link

### ISSUE THREAD

**Issue by lusarz** [ebidel/try-puppeteer#35] opened 2018-09-25 18:50 UTC
Is it possible to generate shareable link from `https://try-puppeteer.appspot.com/` ? 

It may be useful to show issue reproduction in puppeteer repository. For example in cases like here:
https://github.com/GoogleChrome/puppeteer/issues/3299#issuecomment-424456924

**Comment by ebidel** [comment] 2018-09-25 19:14
Dupe of https://github.com/ebidel/try-puppeteer/issues/10

**Closed by ebidel** 2018-09-25 19:14 UTC
